export const WEBSOCKET_CLIENT_CONNECTED = 'WEBSOCKET:CLIENT_CONNECTED';
export const WEBSOCKET_CLIENT_DISCONNECTED = 'WEBSOCKET:CLIENT_DISCONNECTED';
export const WEBSOCKET_LOGGER_CONNECTED = 'WEBSOCKET:LOGGER_CONNECTED';
export const WEBSOCKET_LOGGER_DISCONNECTED = 'WEBSOCKET:LOGGER_DISCONNECTED';
export const WEBSOCKET_MESSAGE = 'WEBSOCKET:MESSAGE';
export const NO_WEBSOCKET_CLIENTS = 'NOWEBSOCKETCLIENTS';