export const LOGIN_REQUEST: string = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS: string = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_ERROR: string = 'LOGIN_REQUEST_ERROR';

export const LOGIN_WITH_JWT_REQUEST: string = 'LOGIN_WITH_JWT_REQUEST';
export const LOGIN_WITH_JWT_REQUEST_SUCCESS: string = 'LOGIN_WITH_JWT_REQUEST_SUCCESS';
export const LOGIN_WITH_JWT_REQUEST_FAILURE: string = 'LOGIN_WITH_JWT_REQUEST_FAILURE';

export const LOGOUT_REQUEST: string = 'LOGOUT_REQUEST';

export const GRID_SORT_BY_COLUMN: string = 'GRID_SORT_BY_COLUMN';

export const DETAILS_REQUEST: string = 'DETAILS_REQUEST';
export const DETAILS_REQUEST_SUCCESS: string = 'DETAILS_REQUEST_SUCCESS';
export const DETAILS_REQUEST_ERROR: string = 'DETAILS_REQUEST_ERROR';

export const SESSION_REQUEST: string = 'SESSION_REQUEST';
export const SESSION_REQUEST_SUCCESS: string = 'SESSION_REQUEST_SUCCESS';
export const SESSION_REQUEST_ERROR: string = 'SESSION_REQUEST_ERROR';

export const SESSIONS_REQUEST: string = 'SESSIONS_REQUEST';
export const SESSIONS_REQUEST_SUCCESS: string = 'SESSIONS_REQUEST_SUCCESS';
export const SESSIONS_REQUEST_ERROR: string = 'SESSIONS_REQUEST_ERROR';

export const SESSION_TOTALS_REQUEST: string = 'SESSION_TOTALS_REQUEST';
export const SESSION_TOTALS_REQUEST_SUCCESS: string = 'SESSION_TOTALS_REQUEST_SUCCESS';
export const SESSION_TOTALS_REQUEST_ERROR: string = 'SESSION_TOTALS_REQUEST_ERROR';

export const SESSIONS_RECENT_REQUEST: string = 'SESSIONS_RECENT_REQUEST';
export const SESSIONS_RECENT_REQUEST_SUCCESS: string = 'SESSIONS_RECENT_REQUEST_SUCCESS';
export const SESSIONS_RECENT_REQUEST_ERROR: string = 'SESSIONS_RECENT_REQUEST_ERROR';

export const EXPORT_RECORDS_REQUEST: string = 'EXPORT_RECORDS_REQUEST';
export const EXPORT_RECORDS_REQUEST_SUCCESS: string = 'EXPORT_RECORDS_REQUEST_SUCCESS';
export const EXPORT_RECORDS_REQUEST_ERROR: string = 'EXPORT_RECORDS_REQUEST_ERROR';
export const EXPORT_RECORDS_CLEAR_REQUEST_ERROR: string = 'EXPORT_RECORDS_CLEAR_REQUEST_ERROR';

export const PAGING_CHANGE_ITEMS_PER_PAGE: string = 'PAGING_CHANGE_ITEMS_PER_PAGE';
export const PAGING_CHANGE_PAGE: string = 'PAGING_CHANGE_PAGE';

// Action types to be dispatched by the user
export const WEBSOCKET_CONNECT = 'WEBSOCKET:CONNECT';
export const WEBSOCKET_DISCONNECT = 'WEBSOCKET:DISCONNECT';
export const WEBSOCKET_SEND = 'WEBSOCKET:SEND';

// Action types dispatched by the WebSocket implementation
export const WEBSOCKET_CONNECTING = 'WEBSOCKET:CONNECTING';
export const WEBSOCKET_OPEN = 'WEBSOCKET:OPEN';
export const WEBSOCKET_DISCONNECTING = 'WEBSOCKET:DISCONNECTING';
export const WEBSOCKET_CLOSED = 'WEBSOCKET:CLOSED';
export const WEBSOCKET_MESSAGE = 'WEBSOCKET:MESSAGE';