export const CLEAR_ERROR: string = 'CLEAR_ERROR';
export const LOGIN_REQUEST: string = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_COMPLETE: string = 'LOGIN_REQUEST_COMPLETE';
export const LOGIN_WITH_JWT_REQUEST: string = 'LOGIN_WITH_JWT_REQUEST';
export const LOGIN_WITH_JWT_REQUEST_COMPLETE: string = 'LOGIN_WITH_JWT_REQUEST_COMPLETE';
export const LOGOUT_REQUEST: string = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_COMPLETE: string = 'LOGOUT_REQUEST_COMPLETE';
export const SESSION_REQUEST: string = 'SESSION_REQUEST';
export const SESSION_REQUEST_COMPLETE: string = 'SESSION_REQUEST_COMPLETE';
export const SESSIONS_REQUEST: string = 'SESSIONS_REQUEST';
export const SESSIONS_REQUEST_COMPLETE: string = 'SESSIONS_REQUEST_COMPLETE';
export const SESSION_TOTALS_REQUEST: string = 'SESSION_TOTALS_REQUEST';
export const SESSION_TOTALS_REQUEST_COMPLETE: string = 'SESSION_TOTALS_REQUEST_COMPLETE';
export const SESSIONS_RECENT_REQUEST: string = 'SESSIONS_RECENT_REQUEST';
export const SESSIONS_RECENT_REQUEST_COMPLETE: string = 'SESSIONS_RECENT_REQUEST_COMPLETE';
export const SESSIONS_FILTER_REQUEST: string = 'SESSIONS_FILTER_REQUEST';
export const SESSIONS_FILTER_REQUEST_COMPLETE: string = 'SESSIONS_FILTER_REQUEST_COMPLETE';
export const EXPORT_RECORDS_REQUEST: string = 'EXPORT_RECORDS_REQUEST';
export const EXPORT_RECORDS_REQUEST_SUCCESS: string = 'EXPORT_RECORDS_REQUEST_SUCCESS';
export const EXPORT_RECORDS_REQUEST_ERROR: string = 'EXPORT_RECORDS_REQUEST_ERROR';
export const EXPORT_RECORDS_CLEAR_REQUEST_ERROR: string = 'EXPORT_RECORDS_CLEAR_REQUEST_ERROR';
export const PAGING_CHANGE_ITEMS_PER_PAGE: string = 'PAGING_CHANGE_ITEMS_PER_PAGE';
export const PAGING_CHANGE_PAGE: string = 'PAGING_CHANGE_PAGE';
export const GRID_SORT_BY_COLUMN: string = 'GRID_SORT_BY_COLUMN';

// action types dispatched from views
export const WEBSOCKET_CLIENT_CONNECTED = 'WEBSOCKET:CLIENT_CONNECTED';
export const WEBSOCKET_CLIENT_DISCONNECTED = 'WEBSOCKET:CLIENT_DISCONNECTED';
export const WEBSOCKET_LOGGER_CONNECTED = 'WEBSOCKET:LOGGER_CONNECTED';
export const WEBSOCKET_LOGGER_DISCONNECTED = 'WEBSOCKET:LOGGER_DISCONNECTED';

export const WEBSOCKET_CONNECT = 'WEBSOCKET:CONNECT';
export const WEBSOCKET_DISCONNECT = 'WEBSOCKET:DISCONNECT';
export const WEBSOCKET_LOGGER_CONNECT = 'WEBSOCKET:CONNECT';
export const WEBSOCKET_LOGGER_DISCONNECT = 'WEBSOCKET:DISCONNECT';
export const WEBSOCKET_SEND = 'WEBSOCKET:SEND';

// action types dispatched by the WebSocket middleware and the server
export const WEBSOCKET_AUTHENTICATED = 'WEBSOCKET:AUTHENTICATED';
export const WEBSOCKET_CONNECTING = 'WEBSOCKET:CONNECTING';
export const WEBSOCKET_OPEN = 'WEBSOCKET:OPEN';
export const WEBSOCKET_DISCONNECTING = 'WEBSOCKET:DISCONNECTING';
export const WEBSOCKET_CLOSED = 'WEBSOCKET:CLOSED';
export const WEBSOCKET_MESSAGE = 'WEBSOCKET:MESSAGE';